### ISSUE TITLE
Ctrl-Q does not quit demo.cs

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1064]

**Comment by BDisp** [comment]
It is the dilemma of the different platforms to interpret the inputs. In `Windows Terminal` the mouse works well and using `PowerShell `the `Enter `key does not work because it interprets as `M`, but using `wsl `in `Windows Terminal` the `Enter `key works perfectly. It's amazing how it works better in `wsl `than in `PowerShell`.
In `ConEmu `neither keyboard nor mouse works minimally and is very slow.
It is necessary to remember that `demo.cs` is using `NetDriver `with the setting `Application.UseSystemConsole = true` and if someone wants to use a native driver for `Windows `or `Unix` it must be set to false.

**Comment by BDisp** [comment]
Correction. In the `Windows Terminal` the mouse only work in `PowerShell `with the `NetDriver`.

**Comment by tig** [comment]
Can't repo. Closing.
