### ISSUE TITLE
Statusbar not showing text on windows

### ISSUE THREAD

**Issue by cartsp** [migueldeicaza/gui.cs#1138]
On windows the status bar with default color scheme shows as below:

![image](https://user-images.githubusercontent.com/1150226/111389301-a6714180-86a8-11eb-8773-1f1b5535df24.png)

on osx shows as:

![image](https://user-images.githubusercontent.com/1150226/111389409-d6204980-86a8-11eb-89f3-3d1670421f30.png)

No properties were set apart from visible on the status bar

**Comment by tig** [comment]
Which terminal are you using on Windows?

What font?

Can you reproduce this with UI Catalog?

**Comment by cartsp** [comment]
It was cmd.exe, the font is Conolas size 16, the UI Catalog seems to display the status bar just fine.

I have tried upgrading the package to the latest prerelease, but that didn't change the result.

The code I am playing with is here:
https://github.com/cartsp/GitGooWee/blob/main/GitGooWee/Program.cs

I am probably doing something wrong, just I was surprised it worked on one and not the other.

**Comment by tznind** [comment]
I think if you move `Application.Init();` to the first line of your program then it will work.

At the moment you are creating the StatusBar before initializing terminal gui.

**Comment by cartsp** [comment]
Thank you very much, that indeed fixed the issue!  I would have never thought to do that, cheers :)  Not sure if this is an issue then or if this is standard behaviour.

Thanks again @tznind

**Comment by BDisp** [comment]
> Not sure if this is an issue then or if this is standard behaviour.

I think we should not consider this case a issue because the abstract class `ConsoleDriver `starts the background color and the foreground color with the default value, which is usually black. The color used by each derived class from the `ConsoleDriver `is only initialized when we invoke the `Application.Init` method and that is why we should only create the other controls after the driver has been initialized.
