### ISSUE TITLE
TableView - Can cells contain Views?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1285]
I'd like to use `TableView`, but I need to (effectively) do "owner draw" in each cell. 

I don't see a 'DrawCell' event (that would be triggered from within `TableView.RenderRow()`).

I also don't see a way I could just assign a `View` to a cell and have the `TableView` be a container for it.

Either would meet my needs, but I suspect the later would be the most powerful. It would, effectively give us a very powerful grid-layout system!

@tznind, what do you think?

**Comment by tznind** [comment]
Direct control of what rendered in the cell is through `RepresentationGetter` in `ColumnStyle`.  If there is no delegate defined for the representation getter then `Format` is used (if the data is numerical, date etc) or `ToString`.

`RenderRow` is private but we could refactor it to be `protected virtual` and make it easier to do fine grained rendering.  That would allow for changing the color or typeface etc of what is rendered.

There are a number of issues:
- The Width of cells is also computed by calling `RepresentationGetter`
- The data model is `System.DataTable` which supports all basic value types in cells (string, double, int, date, time etc) but not classes*.
- Currently every row of the data table can take only 1 row of console height (a lot of the calculations are based on this assumption)

In these respects it is similar to `DataGridView` in winforms rather than `TableLayoutPanel`.  

What data do you want to present? do you need multi row content? We could get into layouts (flow, table etc) but I think to do that we would want a new control rather than make `TableView` fit both use cases (present tabular data and table layout of subviews).

* While the table doesn't support classes you could still add data to the table that you then interpret in the `RepresentationGetter` for example you could create a table 

```
ProcessName,CPU Usage,Memory Usage
1,1,1
2,2,2
3,3,3
```

Then just have a `RepresentationGetter` that returns the requisite value indexed into a list... but that is a bit janky and there might be better ways of doing it.

**Comment by tig** [comment]
Great info. 

I now understand how it works better and it's clearly not going to work the way I had hoped. The real kicker is the limitation on a single row height. I had not considered that, and I now see a) why it's important TableView be that way, and b) how hard it would be to change.

So, do what I want a different way.

Cheers.
