### ISSUE TITLE
TableView - MaxWidth is not honored on last column?

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1286]
![image](https://user-images.githubusercontent.com/585482/117346969-4e132080-ae5d-11eb-9764-1deab39e360a.png)

```c#
var tableView = new TableView () {
	X = 0,
	Y = 0,
	Width = Dim.Fill (),
	Height = Dim.Fill (1),
};
var tableStyle = new TableView.TableStyle ();
tableStyle.AlwaysShowHeaders = true;
tableStyle.ShowHorizontalHeaderUnderline = true;
tableView.Style = tableStyle;

Win.Add (tableView);

var dt = new DataTable ();
tableView.Table = dt;

dt.Columns.Add (new DataColumn ("Scheme", typeof (string)));
tableView.Style.ColumnStyles.Add (tableView.Table.Columns ["Scheme"],
	new TableView.ColumnStyle () { MinWidth = 10, MaxWidth = 10, Alignment = TextAlignment.Left });

var attrs = typeof(ColorScheme).GetProperties ();
foreach (var prop in attrs) {
	dt.Columns.Add (new DataColumn (prop.Name, typeof (string)));
	tableView.Style.ColumnStyles.Add (tableView.Table.Columns [prop.Name], 
		new TableView.ColumnStyle () { MinWidth = 15, MaxWidth = 15, Alignment = TextAlignment.Left });
}
```

IMO, this code should result in the last most column being only 15 cells wide.

@tznind

**Comment by tznind** [comment]
Yes, currently the rendered table always fills the full bounds of the `TableView` control.  This makes the last **visible** column always fill up to the edge of the control.  It is important to consider that the visible column(s) may not be all of them, for example:

If you have many columns e.g: 10 width; 10 width; 10 width; 50 width;  

And your control is width 40 then the first 3 columns would be rendered only and the third column would be increased to 20 width (because there is not enough space for the 50 width one).  Otherwise the table would appear to grow and shrink as you scrolled right.

We could detect whether horizontal scrolling comes into play or not and shrink the table if it doesn't (as is your example above)?

**Comment by tznind** [comment]
We would also need to float the scroll bar (if vertical scrolling was happening) otherwise it would look wierd just hanging off to the right in thin air:

![image](https://user-images.githubusercontent.com/31306100/117376369-e7c3e780-aec8-11eb-8451-b7fec315a7bf.png)

**Comment by BDisp** [comment]
In my opinion, if we use a `MaxWidth` and the last column does not fill in the rest of the width, an extra empty column should be created that can not be used. In this way the width of the columns are respected.
