### ISSUE TITLE
Example:  How to change label text color

### ISSUE THREAD

**Issue by VoIPToys** [migueldeicaza/gui.cs#158]
I can not figure out the syntax to change the text color.  I assume I can change background, foreground, and hotkey colors, either by changing individual attributes or by applying a color scheme.  Can you provide code examples of both approaches?

**Comment by mzhukovs** [comment]
I am able to change the text color, e.g. if lblProgress is a label, like so:
`lblProgress.TextColor = new Terminal.Gui.Attribute((int)Color.Red)`
However, while this does change the text color to red, it also changes the background to black instead of the default terminal blue color and I do not see a property for background color. 
![image](https://user-images.githubusercontent.com/13161978/50063842-130ae680-01e9-11e9-9783-6996289fadc0.png)
Would appreciate any insight, thanks!

p.s. same goes for ColorScheme, did not see background color in the class...

**Comment by PioArchiver** [comment]
I finally figured this out to whom it may concern :)  
```
Colors.Development.Normal = WindowsDriver.MakeColors(ConsoleColor.Black, ConsoleColor.Red);
Driver.SetAttribute(Colors.Development.Normal);
```

**Comment by PioArchiver** [comment]
@mzhukovs I investigated this behavior and found that this is caused due to a call to Clear() before it iterates through the label lines if any are present. 
I believe it is a legit bug.

**Comment by migueldeicaza** [comment]
I added an Attribute.Make to more easily create attributes.

You still need to create your own ColorSchemes
