### ISSUE TITLE
TableView Scrolling Inconsistency

### ISSUE THREAD

**Issue by rmorales87atx** [migueldeicaza/gui.cs#1626]
When scrolling "down" through a TableView, instead of "smoothly" continuing down the list the view instead "jumps" several rows; the other rows are no longer visible unless you manually "scroll up".

![VsDebugConsole_80ZhRTeIZf](https://user-images.githubusercontent.com/3020857/156949359-f23daff9-d31d-4997-92f3-7d1ceb3bca0c.gif)

As shown in the GIF above, once I scroll past line 10 on the screen the view "jumps" and displays lines 11-13; I can no longer see the other lines unless I "scroll up". I expected the view to "smoothly" scroll, showing lines 2-11, 3-12, 4-13 (etc) as I continue to "scroll down".

Scrolling up does seem to work "smoothly" instead of "jumping" the way scrolling down does.

**Comment by tznind** [comment]
Hi @rmorales87atx  thanks for bringing this up.  Please can you check out the fix in https://github.com/migueldeicaza/gui.cs/pull/1627 to make sure it is now behaving as you would expect.

I've fixed vertical scrolling down to only expose the minimum new rows for the newly selected row to be visible instead of jumping down to it.  Note that if `AlwaysShowHeaders` is false then scrolling down off the first page will still reveal multiple new rows since the header is no longer rendered and that space is instead filled with rows.

I've also added `SmoothHorizontalScrolling` which defaults to true.  It functions the same way for scrolling right.  Because `TableView` uses dynamic column sizes (based on content) not all columns are of equal width.  This means sometimes multiple new columns will be revealed scrolling right (e.g. when the column pushed off the left due to the scroll is very wide).

**Comment by rmorales87atx** [comment]
I just started to notice the horizontal scrolling, so I'm glad you managed to catch that.

I'll check out #1627 soon and report back, hopefully within the week. Thank you for the prompt attention.

**Comment by rmorales87atx** [comment]
Hi, I just pulled and tested your code with the fixed TableView. Your changes to vertical & horizontal scrolling work perfectly.
