### ISSUE TITLE
Release a new NuGet package as 1.5

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1669]
Its been 4 months since the last release (1.4.0).  Is there a roadmap for what outstanding issues we want to address before the next release? And/or a timeline for when that will be?  There have been several nice PRs merged since then including keybinding to which the main README refers (that has cause confusion about whether it is a deprecated feature - https://github.com/migueldeicaza/gui.cs/discussions/1667#discussioncomment-2579961).  Another critical bugfix that was merged but not yet released is https://github.com/migueldeicaza/gui.cs/pull/1651 which makes Open/Save dialog break on linux.

**Comment by tig** [comment]
Has it really been that long?! Wow.

I’ll pull together a 1.5 release this week. Maybe today.

-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________
From: Thomas Nind ***@***.***>
Sent: Sunday, April 17, 2022 5:19:36 AM
To: migueldeicaza/gui.cs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [migueldeicaza/gui.cs] NuGet package release (Issue #1669)


Its been 4 months since the last release (1.4.0). Is there a roadmap for what outstanding issues we want to address before the next release? And/or a timeline for when that will be? There have been several nice PRs merged since then including keybinding to which the main README refers (that has cause confusion about whether it is a deprecated feature - #1667 (reply in thread)<https://github.com/migueldeicaza/gui.cs/discussions/1667#discussioncomment-2579961>). Another critical bugfix that was merged but not yet released is #1651<https://github.com/migueldeicaza/gui.cs/pull/1651> which makes Open/Save dialog break on linux.
