### ISSUE TITLE
Intermittent Github Action build failures

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#1712]
Happens frequently. 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/585482/167964685-68a5e194-b824-41bc-beb4-269a98cfcb4a.png">

Could it be the unit tests you added in this PR @tznind?

https://github.com/migueldeicaza/gui.cs/pull/1684

**Comment by tznind** [comment]
Is it always the CharacterMap scenario that fails? 

Looking at the test I can see that it queues a Ctrl+Q keyboard event using `CreateInput ("")` and then does a bunch of setup and runs the scenario.  There is a second shutdown mechanism where after 1s (or 1.5s if CharacterMap) event set up that sends close (same event as Ctrl+Q).

There is a failure condition that says that the 1s close event shouldn't be the one that closes the scenario.

What is the test actually testing? that the Scenarios open without crashing? Or that they are not freezing on startup? 

I'm not sure why it matters whether its the Ctrl+Q or the 'abortCallback' that closes the scenario window? why is having an abortCount of 1 a problem?

Can we solve this problem without compromising the tests purpose by changing the assert to :
`Assert.True (abortCount<=1);`

**Comment by BDisp** [comment]
Mostly but I also get failure on others scenarios. @tig create this scenario to prove the `RequestStop` immediately close a scenario and so there is no abort. When I create the `BackgroundWorkerCollection` and the `SingleBackgroundWorker` scenarios I also was getting test failure because they are `MdiContainers` and by default the log window were open. So the first `RequestStop` close the log windows and only the second call close the scenario and I was getting test fail on the iterations assertion greater than one. So my workaround was to not open the log window by default.
I think that the cause of failures now is some async task that is consume a `Ctrl+Q` keyboard event instead the `Run_All_Scenarios test`. Therefore, asynchronous tasks should be performed in isolation, blocked within the test itself, especially those that take much longer time to perform.

**Comment by tznind** [comment]
I started a branch here to log who gets the readkey but it is now passing 3 builds in a row 😞 .  Could just be luck or could be that logging the output to the test harness slows things down enough that whatever race condition is going on is avoided.

https://github.com/migueldeicaza/gui.cs/compare/main...tznind:all-scenario-tester?expand=1

**Comment by tig** [comment]
Marking as closed as fixed per #1714.

**Comment by tig** [comment]
Reopening as this is still happening.

**Comment by tig** [comment]
Guys, we need to solve this. It happens MOST of the time now when someone submits a PR. I need to ask GitHub to re-run the jobs when this happens in order to start a review.

Any more ideas?
