### ISSUE TITLE
Sub menus auto expand on down arrow

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1739]
**Describe the bug**

When pressing arrow key down in a menu, any sub menus automatically expand and draw focus from the main menu.  The only way for the user to continue down the main list is to press then LEFT arrow to get back into the main tree. 

This is not the way keyboard navigation works in most GUIs e.g. Visual Studio:

![sub-menus](https://user-images.githubusercontent.com/31306100/170002649-822838db-dc75-4348-8cd6-f15875a45864.gif)
_Comparing keyboard navigation of menus that have submenus in Visual Studio vs Terminal.Gui_

**To Reproduce**
1. Create menu with multiple submenus
2. Press down arrow multiple times

**Expected behavior**
It should be possible to keep scrolling down a menu using only up/down.  Submenus should only expand on pressing RIGHT arrow (when using keyboard only navigation).

**Comment by BDisp** [comment]
Through the mouse the sub menus are auto expanding. So, I understand that they must have different behaviors.
You have to be aware that currently if you press the right arrow key the next menu from the menu bar will be selected.
Therefore the solution is, if the current opened menu has no sub menu, pressing the right arrow key the next menu from the menu bar will be selected. Otherwise the sub menu of the current opened menu will be opened.

**Comment by tznind** [comment]
> Therefore the solution is, if the current opened menu has no sub menu, pressing the right arrow key the next menu from the menu bar will be selected. Otherwise the sub menu of the current opened menu will be opened. The same logic have to be used for the current sub menu opened.

That sounds perfect 💯
