### ISSUE TITLE
Buttons blank after updating to 1.6.3 (from 1.5.0)

### ISSUE THREAD

**Issue by tznind** [migueldeicaza/gui.cs#1750]
**Describe the bug**
When running the following code in 1.5.0 you get a button with the text "Info" as expected.  After updating to 1.6.3 it is blank (see screenshots).

```csharp
Application.Init();

var w = new Window();

var btn = new Button
{
    Text = "Info",
    IsDefault = false,
};
w.Add(btn);
Application.Run(w);
Application.Shutdown();

```

**Screenshots**
![image](https://user-images.githubusercontent.com/31306100/170695046-356c9673-7e67-4759-8bc1-75d324966480.png)
_Running with 1.5.0_

![image](https://user-images.githubusercontent.com/31306100/170695067-11760e91-9540-45f4-9937-49ab7cf1fef3.png)
_Running with 1.6.3_

**Desktop (please complete the following information):**
 - OS: Windows
 - Terminal: Powershell

**Comment by jas88** [comment]
Looks like a bug introduced by https://github.com/migueldeicaza/gui.cs/commit/c561016423a579024ba5a55cc98a67dcb47f10e0 - skipping the call to Update leaves a window where creating a new Button then setting the text, instead of passing the text as a constructor argument, fails to update when needed. (It gets Initialized with the default blank value, then Text gets updated but without triggering Update, and finally IsInitialized presumably gets set - but too late, because the change of value has been ignored.) @BDisp ?

**Comment by BDisp** [comment]
> Looks like a bug introduced by [c561016](https://github.com/migueldeicaza/gui.cs/commit/c561016423a579024ba5a55cc98a67dcb47f10e0) - skipping the call to Update leaves a window where creating a new Button then setting the text, instead of passing the text as a constructor argument, fails to update when needed. (It gets Initialized with the default blank value, then Text gets updated but without triggering Update, and finally IsInitialized presumably gets set - but too late, because the change of value has been ignored.) @BDisp ?

The Update run before the Redraw, so it's not the cause.

Did you both already change the upstream for the new gui.cs repo? I didn't yet.

I updated the Terminal.Gui nuget package to 1.6.3 on the StandaloneExample solution and I haven't issues.

![solution](https://user-images.githubusercontent.com/13117724/170707030-fab85932-334b-4803-bbde-45bc0f89a4b6.png)
![standalone](https://user-images.githubusercontent.com/13117724/170707058-2172e4ca-246f-4983-9ecc-3d441d0b0f32.png)

**Comment by jas88** [comment]
@BDisp Upstream? I was testing against the released Nuget package, 1.6.3. You won't see this issue with StandaloneExample, because it creates the button as "new Button("foo") {}" instead of "new Button() { Text="foo" }", which results in a slightly different sequence of operations triggering this bug: Text starts off as an empty string in @tznind 's test case above, then gets changed to "Info" but your commit suppresses that change.

**Comment by tznind** [comment]
Here is a test

```csharp
[Fact, AutoInitShutdown]
public void TestButton_BlankConstructor()
{
	var btn = new Button {
		Text = "Test"
	};
	btn.ColorScheme = new ColorScheme ();
	btn.Redraw (btn.Bounds);
	GraphViewTests.AssertDriverContentsAre ("[ Test ]", output);
}
```

Output is:
```
  Message: 
Assert.Equal() Failure
            ↓ (pos 2)
Expected: [ Test ]
Actual:   [  ]
            ↑ (pos 2)
```

**Comment by BDisp** [comment]
But that commit was necessary because of another issue on displaying button text with wide runes.
Run the test `Update_Only_On_Or_After_Initialize` and it will fail.
The solution is using another check than the `IsInitialized`. I'll will suggest in the pr #1752.

**Comment by jas88** [comment]
@BDisp I think that's because TextFormatter erroneously caches the RuneWidth, I have a workaround (for Button at least) inbound.

**Comment by jas88** [comment]
I don't think the logic that if the existing width in columns matches the number of runes in the new string then the width doesn't need recalculated is actually correct - it's close enough to pass in a lot of cases but there are corner cases which will trip people up. Are you sure this is right?! https://github.com/migueldeicaza/gui.cs/blob/2971fc91345884e6ad477aeb88acc8f1cd67b249/Terminal.Gui/Core/TextFormatter.cs#L139

**Comment by BDisp** [comment]
> I don't think the logic that if the existing width in columns matches the number of runes in the new string then the width doesn't need recalculated is actually correct - it's close enough to pass in a lot of cases but there are corner cases which will trip people up. Are you sure this is right?!
> 
> https://github.com/migueldeicaza/gui.cs/blob/2971fc91345884e6ad477aeb88acc8f1cd67b249/Terminal.Gui/Core/TextFormatter.cs#L139

Thanks. Replace with this one, please.
`if (text.RuneCount > 0 && (Size.Width == 0 || Size.Height == 0 || Size.Width != text.ConsoleWidth)) {`

**Comment by BDisp** [comment]
That fix it. Remove the workaround and add this test please.
```cs

		[Fact, AutoInitShutdown]
		public void Update_Parameterless_Only_On_Or_After_Initialize ()
		{
			var btn = new Button () {
				X = Pos.Center (),
				Y = Pos.Center (),
				Text = "Say Hello 你"
			};
			var win = new Window () {
				Width = Dim.Fill (),
				Height = Dim.Fill (),
				Title = "Test Demo 你"
			};
			win.Add (btn);
			Application.Top.Add (win);

			Assert.False (btn.IsInitialized);

			Application.Begin (Application.Top);
			((FakeDriver)Application.Driver).SetBufferSize (30, 5);

			Assert.True (btn.IsInitialized);
			Assert.Equal ("Say Hello 你", btn.Text);
			Assert.Equal ("[ Say Hello 你 ]", btn.TextFormatter.Text);
			Assert.Equal (new Rect (0, 0, 16, 1), btn.Bounds);

			var expected = @"
┌ Test Demo 你 ──────────────┐
│                            │
│      [ Say Hello 你 ]      │
│                            │
└────────────────────────────┘
";

			var pos = GraphViewTests.AssertDriverContentsWithFrameAre (expected, output);
			Assert.Equal (new Rect (0, 0, 30, 5), pos);
		}

```

**Comment by jas88** [comment]
I've applied the proper fix to TextFormatter, removed that workaround from Button.cs and added a regression test that catches this corner case (new rune count == old column count), plus added your new test case for Button.

Update still needs to be called every time Text changes, otherwise Text and TextFormatter will get out of sync which triggers the original bug on this thread.

**Comment by BDisp** [comment]
Thanks. Be aware that the Button.Text is not the same than the TextFormatter.Text. This one is who will used to draw.

**Comment by jas88** [comment]
Yes, that was the root problem behind the issue here: suppressing Update meant the button appeared with the wrong text (the old value from TextFormatter, since the new value in Text never got copied over).

**Comment by BDisp** [comment]
> Here is a test
> 
> ```cs
> [Fact, AutoInitShutdown]
> public void TestButton_BlankConstructor()
> {
> 	var btn = new Button {
> 		Text = "Test"
> 	};
> 	btn.ColorScheme = new ColorScheme ();
> 	btn.Redraw (btn.Bounds);
> 	GraphViewTests.AssertDriverContentsAre ("[ Test ]", output);
> }
> ```

@jas88 I think is good idea to include the @tznind test too, to guarantee that this never fail again, thanks.

**Comment by jas88** [comment]
@BDisp There's a variant of that test incorporated in #1752 (lines 29 and 169 on in ButtonTests.cs) that catches the issue here if it recurs; I also added your Update_Parameterless_Only_On_Or_After_Initialize test which covers this. We've got good coverage of both the Text v TextFormatter desync and consistency between Text/TextFormatter and the resulting display contents with that PR now.

**Comment by FreddieMercurial** [comment]
love all your work
