### ISSUE TITLE
Exceptions wreak havoc on the UI

### ISSUE THREAD

**Issue by bryancostanich** [migueldeicaza/gui.cs#248]
I created a simple demo app (code below), and when I run it, i get an exception, but it's basically unreadable:

<img width="1402" alt="Screen Shot 2019-08-28 at 2 27 17 PM" src="https://user-images.githubusercontent.com/947633/63893918-36a14600-c9a0-11e9-9e7a-935814d37fa7.png">

repro code below (i've already solved the actual issue):
```csharp
using System;
using Terminal.Gui;

namespace Meadow.Provisioning.Gui
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            Application.Init();
            var top = Application.Top;

            ConstructUI(top);

            Application.Run();
        }

        private static void ConstructUI(Toplevel top)
        {
            // Creates the top-level window to show
            var win = new Window("MyApp") {
                X = 0,
                Y = 1, // Leave one row for the toplevel menu

                // By using Dim.Fill(), it will automatically resize without manual intervention
                Width = Dim.Fill(),
                Height = Dim.Fill()
            };
            top.Add(win);

            // Creates a menubar, the item "New" has a help menu.
            var menu = new MenuBar(new MenuBarItem[] {
            new MenuBarItem ("_File", new MenuItem [] {
                new MenuItem ("_Quit", "", () => { if (Quit ()) top.Running = false; })
                }),
            });
            top.Add(menu);

            // Dynamically computed
            var label = new Label("Welcome to the Meadow Provisioning tool. Brought to you by the 90s.") {
                X = 1,
                //Y = Pos.Left(win),
                Y = Pos.Left(top),
                //Y = Pos.Left(),
                Width = Dim.Fill(),
                Height = 1
            };
            top.Add(label);
        }

        static bool Quit()
        {
            var n = MessageBox.Query(50, 7, "Quit", "Are you sure you want to quit?", "Yes", "No");
            return n == 0;
        }

    }
}

```

**Comment by bryancostanich** [comment]
Try on mac?

**Comment by drk-mtr** [comment]
Another example:

![Screenshot 2019-10-05 at 14 39 27](https://user-images.githubusercontent.com/40315783/66255663-49b4ec00-e77e-11e9-996a-b78e7c545464.png)

I am having a play with https://github.com/DieselMeister/Terminal.Gui.Elmish

I believe the issue I'm experiencing is with the wrapper itself, rather than gui.cs - but the effect when it goes wrong is rather interesting!

This is using iterm2 and zsh on mac, with the `examples/Elmish.Console.Elements` project within that github repo.

Please note I may not be understanding what's going on correctly here and it may be an unrelated issue. One thing I noticed is that when I close the app after experiencing this issue, output continues to be written to the console - so I think the wrapper I'm using is hammering some input buffer and the update loop can't keep up.

**Comment by tig** [comment]
If you can provide a repro without the emish wrapper please do, and re-open this issue. Thanks.
