### ISSUE TITLE
MessageBox does not deal with long text well; takes size parameters but they are useless

### ISSUE THREAD

**Issue by tig** [migueldeicaza/gui.cs#432]
the `MessageBox` has 3 methods to pop message boxes: 'Query', 'ErrorQuery', and 'QueryFull'. All based on `QueryFull`.

These methods all take a `height` and `width`.

`width` is completely ignored. The width of the `MessageBox` ends up being whatever width is required to display the `message`. 

`height` is useless. It must be at least `6` for the `MessageBox` to show, but making it bigger does nothing because `message` doesn't wrap if it's too big.

Suggestion: Honor `height` and `width` and have the `message` be implemented by a `TextView` so that the text wraps if too long. 

That said, has anyone considered re-implementing `Label` as a read-only `TextView`, this way it would get wrap support for free.....

**Comment by tig** [comment]
UI Catalog `MessageBoxes` scenario shows this bug.

**Comment by BDisp** [comment]
In my opinion, the MessageBox should have a minimum size and a maximum size, based on the size of the top-level that, if it cannot support the whole text, it's wrap if it is too large. It could be a label but if it is necessary to copy its content a read only TextView would be a great idea. The last time I changed it I ensured that the text did not write outside the window in its width, but I did not guarantee the same in relation to the height because there would have to be another intervention, namely the text wrap. Go for it and congratulations on your great work.
