### ISSUE TITLE
MessageBox not drawing well when opened on a small screen.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#557]
![message-box](https://user-images.githubusercontent.com/13117724/83057853-62e11480-a04f-11ea-999f-c82e936cfe6d.png)

**Comment by tig** [comment]
Related: #432 & #299 

In my opinion we should do the following:

1. Implement a robust read-only text engine that supports:
   - left, right, center, justifiied justifiction
   - line wrap (both word and character based)
   - rendering ANSI color/formatting sequences
2. Put this text engine under `Label`
3. Use `Label` as a child control (or renderer) inside all other controls that display read-only text:  `Window.Title`, `MessageBox`, `TextView`, etc...

@migueldeicaza has been doing work on a better text editor component for `SwiftTerm`. I suspect that work will not be useful to `Terminal.Gui` since it's probably tied to iOS. I think having a robust *read-only* text engine is more important that having BOTH that and an `editor`. And I'm not convinced they need to be based on the same thing (although one could argue that you'd read-only to just be a read-only version of edit.
