### ISSUE TITLE
[Question] Ability to Copy Text from Selected Region in View

### ISSUE THREAD

**Issue by valkyrienyanko** [migueldeicaza/gui.cs#631]
I have a `View` with several `Label` views attached to it, I want to make it so I can Click + Drag to select a region which will be highlighted with black text and a white background, then when I press Enter, I want to copy that region of text. Is there any easy way to do this?

Below you can get an idea of what my view looks like with the labels being populated in it. There's also a text input field right under the last label entry.
![Preview](https://i.gyazo.com/70f800df26738704f659389fec26f8ff.gif)

Right now I can't do any of the click + drag / enter behavior I described above.

**Comment by tznind** [comment]
[Writting to the OS clipboard in a dotnet core is quite fiddly](https://stackoverflow.com/questions/44205260/net-core-copy-to-clipboard).  You are also proposing dragging across multiple views at once so that makes things complicated.  If the screen is updating asynchronously then the region you start dragging isn't going to be the same as when you end the dragging.

Your OS console may already support copying rectangular sections of the screen for copy/paste (e.g. right click Mark or drag selection and Ctrl+Shift+C).

![image](https://user-images.githubusercontent.com/31306100/127407475-72def22d-11e7-4a69-a982-78be0c691da9.png)
