### ISSUE TITLE
Application.Loaded is useless if it is to be called by more than one object.

### ISSUE THREAD

**Issue by BDisp** [migueldeicaza/gui.cs#721]
The problem with `Application.Loaded` is that it belongs to the `Application `class only. It must belong to the `View `class and call all views of subscribers who implement it. The `Application `class should only invoke the `Loaded `event.

**Comment by tig** [comment]
I agree that the value of `Application.Loaded` is minimal (not useless). But the problem is not that it's not on `View`, the problem is folks are using it for things it should not be used for. They are doing that because, previously, `View.LayoutComplete` and `View.Resized` didn't exist. 

We may also be missing an initialization event on `View` that happens once the view has been registered by `Add` on the SuperView, but I don't understand why `LayoutComplete` doesn't work for that.

Loaded means Loaded and is called from `Application.Run`. This means it is NEVER called if the `View` is created after the app ha started.

**Comment by BDisp** [comment]
If it is only necessary to call once when creating the view, `LayoutComplete `is not recommended. I will try to present another alternative that calls so much when adding to `SuperView `even if it is added dynamically after the application is already running.
