### ISSUE TITLE
How do I disable a view like a Button?

### ISSUE THREAD

**Issue by brian-pickens-web** [migueldeicaza/gui.cs#884]
Hello, 

I am trying to change a button to a disabled state. Since there isn't a property like that, is there a way to code for a disabled state?

**Comment by BDisp** [comment]
You can use the `CanFocus`, `Visible `or `TabStop `properties.

**Comment by patriksvensson** [comment]
While all those properties work, it would be nice with a `Disabled` button that greyed out the button, making it obvious to the user that it's been disabled. `CanFocus` and `TabStop` does not accomplish this. `Visible` doesn't even show that there is a button to be clicked.

I would be happy to submit a pull request for this since I looked through the code base for this exact functionality.

**Comment by BDisp** [comment]
I think it would be fine. I thought about that too. Go ahead. Thanks.
