### ISSUE TITLE
Resizing terminal doesn't seem to work on linux

### ISSUE THREAD

**Issue by Mgamerz** [migueldeicaza/gui.cs#983]
Been a while since I've worked on my console version of my app, and noticed lots of stuff has changed since I was last here. One of the new issues I noticed (on the latest commit - I just pulled master before making this) is that on Linux the terminal size doesn't cause the application to refresh the interface, and it's stuck in the original size, which makes it nearly unusable.

![image](https://user-images.githubusercontent.com/2738836/97492657-77407a80-1929-11eb-9ffb-6d7492eb6aa4.png)

Right screenshot is on Ubuntu 20.04.

I've also had some reports where users mouse over things and it causes the application to detect clicks, or inputs of some kind. One user had it simulate 12 clicks on a download button - but I don't think this is due to this gui framework, I've noticed linux just kind of thinks mouseover is some sort of input, e.g. i have terminals that are 'press any key to continue' (like when a console app ends in the debugger) and mousing over them immediately closes them. I don't use Linux that often so not sure if this is intended behavior of a terminal on Linux?

**Comment by BDisp** [comment]
Weird. This only happened to me when I used the PR #953 that I submitted but put it as draft because it is not sufficiently acceptable. As for the mouse, it really had a strange behavior with the appearance of `Ubuntu 20.04` but I have already fixed it.

**Comment by tig** [comment]
@Mgamerz would you be able to pull down the latest RC and let us know if we can close this issue?

**Comment by kaesaecracker** [comment]
@tig I have the same problem using v1.0. Also running Linux, both when using the VS Code built-in terminal and Xfce Terminal.

**Comment by BDisp** [comment]
@kaesaecracker  see this discussion #1304

**Comment by BDisp** [comment]
@tig I think this can be closed, because the resizing is already working, although I don't like it very much, because I'm trying to implement a system clipboard with `OS` interaction, but even using `xsel` or `xclip` on `Linux`, the output appears corrupt. The culprit is `Console.Out.Write ("\x1b[?1h")`, wich causing `ncurses` to be unstable. If anyone know what is going on here, please say something. Thanks.

**Comment by BDisp** [comment]
Well, when the terminal was freezes before and we needed to write `reset` to restore the terminal, only happens if we run the application from the `UICatalog/bin/Debug/net5.0/` folder:
`dotnet ./UICatalog.dll`

If we run the follow from the `UICatalog` where is the project file the terminal doesn't freezes.
`dotnet run`

I think it's better to revert the implementations that I did to `ncurses` working properly and I will to implement the clipboard improvement.

What do you thinks?
